services:
  tools-ms:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PICTURAS_AVAILABLE_TOOLS=crop,scale,addBorder,adjustBrightness,adjustContrast,rotate,blur,ocr,grayscale,binarize
      - RUST_LOG=INFO
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - PICTURAS_RESULTS_EXCHANGE=picturas.tools
      - PICTURAS_RESULTS_ROUTING_KEY=results
    volumes:
      - images:/images
    networks:
      - picturas-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      projects-ms:
        condition: service_healthy
