services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - VITE_API_BASE=http://localhost/api/v1
      - PORT=3000

    networks:
      - picturas-network
    depends_on:
      - projects-ms
      - tools-ms