include:
  - tools-ms/docker-compose.yml
  - projects-ms/docker-compose.yml
  - users-ms/docker-compose.yml
  - picturas-bg-remover-tool-ms/docker-compose.yml

networks:
  picturas-network:

volumes:
  images: