name: picturas-dev
services:
  db-dev:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  rabbitmq-dev:
    image: rabbitmq:4-management-alpine
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq/
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 30s
  redis-dev:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis
volumes:
  db:
  rabbitmq-data:
  rabbitmq-logs:
