services:
  db-subs-ms:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    networks:
      - picturas-network
    volumes:
      - db:/var/lib/postgresql/data
  subs-ms:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_PORT: ${PG_PORT}
      PG_DATABASE: ${PG_DATABASE}
      STRIPE_SECRET_KEY: /run/secrets/stripe_secret_key
      WEBHOOK_SECRET: /run/secrets/webhook_secret
    secrets:
      - stripe_secret_key
      - webhook_secret
    networks:
      - picturas-network
    volumes:
      - ../keys:/keys
    depends_on:
      - db
    env_file:
      - .env

secrets:
  stripe_secret_key:
    file: ./stripe_secret_key.txt
  webhook_secret:
    file: ./webhook_secret.txt

volumes:
  db-sub-ms: