services:
  db-subs-ms:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    networks:
      - picturas-network
    volumes:
      - db:/var/lib/postgresql/data
  subs-ms:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_PORT: ${PG_PORT}
      PG_DATABASE: ${PG_DATABASE}
    volumes:
      - ../keys:/keys
    networks:
      - picturas-network
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db-sub-ms: