services:
  bg-remover-ms:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_REQUESTS_QUEUE_NAME
      - RABBITMQ_RESULTS_EXCHANGE
      - RABBITMQ_RESULTS_ROUTING_KEY
      - PICTURAS_LOG_LEVEL=INFO
      - PICTURAS_MS_NAME
      - PICTURAS_NUM_THREADS
    volumes:
      - images:/images
    networks:
      - picturas-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      projects-ms:
        condition: service_healthy