services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: picturas
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_PORT: ${PG_PORT}
      PICTURAS_BIND_ADDRESS: ${PICTURAS_BIND_ADDRESS}
      PICTURAS_IMAGE_FOLDER: ${PICTURAS_IMAGE_FOLDER}
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  db: