### Create a project
POST http://localhost:8000/api/v1/projects
Content-Type: application/json
x-user-id: 4d5b989d-78b1-456c-a9e3-07b0b786bdf1
x-user-name: Chico
x-user-email: mail@chicoferreira.dev

{
  "name": "My Project"
}

> {%
  client.global.set("project", response.body.id);
%}

### Gets a project
GET http://localhost:8000/api/v1/projects/{{project}}
Content-Type: application/json
x-user-id: 4d5b989d-78b1-456c-a9e3-07b0b786bdf1
x-user-name: Chico
x-user-email: mail@chicoferreira.dev

{
  "name": "My Project"
}

### Uploads an image to a project
POST http://localhost:8000/api/v1/projects/{{project}}/images
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
x-user-id: 4d5b989d-78b1-456c-a9e3-07b0b786bdf1
x-user-name: Chico
x-user-email: mail@chicoferreira.dev

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/png

< ./image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

> {%
  client.global.set("image", response.body[0].id);
%}

### Gets an image from a project
GET http://localhost:8000/api/v1/projects/{{project}}/images/{{image}}

### Gets all images from a project
GET http://localhost:8000/api/v1/projects/{{project}}/images

### Deletes an image from a project
DELETE http://localhost:8000/api/v1/projects/{{project}}/images/{{image}}